// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.3
// source: bets_service.proto

package betservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Confirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bets_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_bets_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_bets_service_proto_rawDescGZIP(), []int{0}
}

func (x *Confirmation) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Confirmation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaceBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login   string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	MatchID string `protobuf:"bytes,2,opt,name=matchID,proto3" json:"matchID,omitempty"`
	TeamPos int32  `protobuf:"varint,3,opt,name=team_pos,json=teamPos,proto3" json:"team_pos,omitempty"`
	Amount  int32  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bets_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bets_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_bets_service_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBetRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PlaceBetRequest) GetMatchID() string {
	if x != nil {
		return x.MatchID
	}
	return ""
}

func (x *PlaceBetRequest) GetTeamPos() int32 {
	if x != nil {
		return x.TeamPos
	}
	return 0
}

func (x *PlaceBetRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CalculateOddsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchID string `protobuf:"bytes,1,opt,name=matchID,proto3" json:"matchID,omitempty"`
}

func (x *CalculateOddsRequest) Reset() {
	*x = CalculateOddsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bets_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateOddsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateOddsRequest) ProtoMessage() {}

func (x *CalculateOddsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bets_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateOddsRequest.ProtoReflect.Descriptor instead.
func (*CalculateOddsRequest) Descriptor() ([]byte, []int) {
	return file_bets_service_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateOddsRequest) GetMatchID() string {
	if x != nil {
		return x.MatchID
	}
	return ""
}

type CalculateOddsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OddsTeam1 float64 `protobuf:"fixed64,1,opt,name=oddsTeam1,proto3" json:"oddsTeam1,omitempty"`
	OddsTeam2 float64 `protobuf:"fixed64,2,opt,name=oddsTeam2,proto3" json:"oddsTeam2,omitempty"`
}

func (x *CalculateOddsResponse) Reset() {
	*x = CalculateOddsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bets_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateOddsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateOddsResponse) ProtoMessage() {}

func (x *CalculateOddsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bets_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateOddsResponse.ProtoReflect.Descriptor instead.
func (*CalculateOddsResponse) Descriptor() ([]byte, []int) {
	return file_bets_service_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateOddsResponse) GetOddsTeam1() float64 {
	if x != nil {
		return x.OddsTeam1
	}
	return 0
}

func (x *CalculateOddsResponse) GetOddsTeam2() float64 {
	if x != nil {
		return x.OddsTeam2
	}
	return 0
}

var File_bets_service_proto protoreflect.FileDescriptor

var file_bets_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x65, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x65, 0x74, 0x73, 0x22, 0x42, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74,
	0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x44, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x4f, 0x64, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x22, 0x53, 0x0a, 0x15, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x4f, 0x64, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6f, 0x64, 0x64, 0x73, 0x54, 0x65, 0x61, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6f, 0x64, 0x64, 0x73, 0x54, 0x65, 0x61, 0x6d, 0x31, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x64, 0x64, 0x73, 0x54, 0x65, 0x61, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6f, 0x64, 0x64, 0x73, 0x54, 0x65, 0x61, 0x6d, 0x32, 0x32, 0x87, 0x01, 0x0a, 0x04,
	0x42, 0x65, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74,
	0x12, 0x15, 0x2e, 0x62, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x65, 0x74, 0x73, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0d, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x1a, 0x2e, 0x62,
	0x65, 0x74, 0x73, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x64, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x65, 0x74, 0x73, 0x2e,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x64, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x62, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bets_service_proto_rawDescOnce sync.Once
	file_bets_service_proto_rawDescData = file_bets_service_proto_rawDesc
)

func file_bets_service_proto_rawDescGZIP() []byte {
	file_bets_service_proto_rawDescOnce.Do(func() {
		file_bets_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bets_service_proto_rawDescData)
	})
	return file_bets_service_proto_rawDescData
}

var file_bets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bets_service_proto_goTypes = []interface{}{
	(*Confirmation)(nil),          // 0: bets.Confirmation
	(*PlaceBetRequest)(nil),       // 1: bets.PlaceBetRequest
	(*CalculateOddsRequest)(nil),  // 2: bets.CalculateOddsRequest
	(*CalculateOddsResponse)(nil), // 3: bets.CalculateOddsResponse
}
var file_bets_service_proto_depIdxs = []int32{
	1, // 0: bets.Bets.PlaceBet:input_type -> bets.PlaceBetRequest
	2, // 1: bets.Bets.CalculateOdds:input_type -> bets.CalculateOddsRequest
	0, // 2: bets.Bets.PlaceBet:output_type -> bets.Confirmation
	3, // 3: bets.Bets.CalculateOdds:output_type -> bets.CalculateOddsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bets_service_proto_init() }
func file_bets_service_proto_init() {
	if File_bets_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bets_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bets_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bets_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateOddsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bets_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateOddsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bets_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bets_service_proto_goTypes,
		DependencyIndexes: file_bets_service_proto_depIdxs,
		MessageInfos:      file_bets_service_proto_msgTypes,
	}.Build()
	File_bets_service_proto = out.File
	file_bets_service_proto_rawDesc = nil
	file_bets_service_proto_goTypes = nil
	file_bets_service_proto_depIdxs = nil
}
