# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fuser_auth.proto".\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"\x1a\n\tUserLogin\x12\r\n\x05login\x18\x01 \x01(\t"D\n\x11LoginConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t"\x17\n\x06\x41mount\x12\r\n\x05value\x18\x01 \x01(\x01",\n\x0bTransaction\x12\r\n\x05login\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01"0\n\x0c\x43onfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd0\x01\n\x08UserAuth\x12$\n\x08Register\x12\t.UserInfo\x1a\r.Confirmation\x12-\n\x05Login\x12\x10.UserCredentials\x1a\x12.LoginConfirmation\x12\x1e\n\x07\x42\x61lance\x12\n.UserLogin\x1a\x07.Amount\x12&\n\x07\x44\x65posit\x12\x0c.Transaction\x1a\r.Confirmation\x12\'\n\x08Withdraw\x12\x0c.Transaction\x1a\r.Confirmationb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_auth_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_USERINFO"]._serialized_start = 19
    _globals["_USERINFO"]._serialized_end = 65
    _globals["_USERCREDENTIALS"]._serialized_start = 67
    _globals["_USERCREDENTIALS"]._serialized_end = 120
    _globals["_USERLOGIN"]._serialized_start = 122
    _globals["_USERLOGIN"]._serialized_end = 148
    _globals["_LOGINCONFIRMATION"]._serialized_start = 150
    _globals["_LOGINCONFIRMATION"]._serialized_end = 218
    _globals["_AMOUNT"]._serialized_start = 220
    _globals["_AMOUNT"]._serialized_end = 243
    _globals["_TRANSACTION"]._serialized_start = 245
    _globals["_TRANSACTION"]._serialized_end = 289
    _globals["_CONFIRMATION"]._serialized_start = 291
    _globals["_CONFIRMATION"]._serialized_end = 339
    _globals["_USERAUTH"]._serialized_start = 342
    _globals["_USERAUTH"]._serialized_end = 550
# @@protoc_insertion_point(module_scope)
