# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_gen.user_auth_pb2 as user__auth__pb2


class UserAuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/UserAuth/Register",
            request_serializer=user__auth__pb2.UserInfo.SerializeToString,
            response_deserializer=user__auth__pb2.Confirmation.FromString,
        )
        self.Login = channel.unary_unary(
            "/UserAuth/Login",
            request_serializer=user__auth__pb2.UserCredentials.SerializeToString,
            response_deserializer=user__auth__pb2.LoginConfirmation.FromString,
        )
        self.Balance = channel.unary_unary(
            "/UserAuth/Balance",
            request_serializer=user__auth__pb2.UserLogin.SerializeToString,
            response_deserializer=user__auth__pb2.Amount.FromString,
        )
        self.Deposit = channel.unary_unary(
            "/UserAuth/Deposit",
            request_serializer=user__auth__pb2.Transaction.SerializeToString,
            response_deserializer=user__auth__pb2.Confirmation.FromString,
        )
        self.Withdraw = channel.unary_unary(
            "/UserAuth/Withdraw",
            request_serializer=user__auth__pb2.Transaction.SerializeToString,
            response_deserializer=user__auth__pb2.Confirmation.FromString,
        )


class UserAuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Balance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserAuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=user__auth__pb2.UserInfo.FromString,
            response_serializer=user__auth__pb2.Confirmation.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=user__auth__pb2.UserCredentials.FromString,
            response_serializer=user__auth__pb2.LoginConfirmation.SerializeToString,
        ),
        "Balance": grpc.unary_unary_rpc_method_handler(
            servicer.Balance,
            request_deserializer=user__auth__pb2.UserLogin.FromString,
            response_serializer=user__auth__pb2.Amount.SerializeToString,
        ),
        "Deposit": grpc.unary_unary_rpc_method_handler(
            servicer.Deposit,
            request_deserializer=user__auth__pb2.Transaction.FromString,
            response_serializer=user__auth__pb2.Confirmation.SerializeToString,
        ),
        "Withdraw": grpc.unary_unary_rpc_method_handler(
            servicer.Withdraw,
            request_deserializer=user__auth__pb2.Transaction.FromString,
            response_serializer=user__auth__pb2.Confirmation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "UserAuth", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class UserAuth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UserAuth/Register",
            user__auth__pb2.UserInfo.SerializeToString,
            user__auth__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UserAuth/Login",
            user__auth__pb2.UserCredentials.SerializeToString,
            user__auth__pb2.LoginConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Balance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UserAuth/Balance",
            user__auth__pb2.UserLogin.SerializeToString,
            user__auth__pb2.Amount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Deposit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UserAuth/Deposit",
            user__auth__pb2.Transaction.SerializeToString,
            user__auth__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Withdraw(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UserAuth/Withdraw",
            user__auth__pb2.Transaction.SerializeToString,
            user__auth__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
