# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bets_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x62\x65ts_service.proto\x12\x04\x62\x65ts"0\n\x0c\x43onfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"S\n\x0fPlaceBetRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x0f\n\x07matchID\x18\x02 \x01(\t\x12\x10\n\x08team_pos\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05"\'\n\x14\x43\x61lculateOddsRequest\x12\x0f\n\x07matchID\x18\x01 \x01(\t"=\n\x15\x43\x61lculateOddsResponse\x12\x11\n\toddsTeam1\x18\x01 \x01(\x01\x12\x11\n\toddsTeam2\x18\x02 \x01(\x01\x32\x87\x01\n\x04\x42\x65ts\x12\x35\n\x08PlaceBet\x12\x15.bets.PlaceBetRequest\x1a\x12.bets.Confirmation\x12H\n\rCalculateOdds\x12\x1a.bets.CalculateOddsRequest\x1a\x1b.bets.CalculateOddsResponseB\x18Z\x16proto_gen/betservicepbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bets_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\026proto_gen/betservicepb"
    _globals["_CONFIRMATION"]._serialized_start = 28
    _globals["_CONFIRMATION"]._serialized_end = 76
    _globals["_PLACEBETREQUEST"]._serialized_start = 78
    _globals["_PLACEBETREQUEST"]._serialized_end = 161
    _globals["_CALCULATEODDSREQUEST"]._serialized_start = 163
    _globals["_CALCULATEODDSREQUEST"]._serialized_end = 202
    _globals["_CALCULATEODDSRESPONSE"]._serialized_start = 204
    _globals["_CALCULATEODDSRESPONSE"]._serialized_end = 265
    _globals["_BETS"]._serialized_start = 268
    _globals["_BETS"]._serialized_end = 403
# @@protoc_insertion_point(module_scope)
