# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13match_service.proto\x12\x0cmatchservice"p\n\x05Match\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05team1\x18\x02 \x01(\t\x12\r\n\x05team2\x18\x03 \x01(\t\x12\x12\n\nmatch_time\x18\x04 \x01(\t\x12)\n\x06status\x18\x05 \x01(\x0e\x32\x19.matchservice.MatchStatus"C\n\x0f\x41\x64\x64MatchRequest\x12\r\n\x05team1\x18\x01 \x01(\t\x12\r\n\x05team2\x18\x02 \x01(\t\x12\x12\n\nmatch_time\x18\x03 \x01(\t"6\n\x16UpdateMatchTimeRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08new_time\x18\x02 \x01(\t"\x1e\n\x10MarkMatchRequest\x12\n\n\x02id\x18\x01 \x01(\t"3\n\rMatchResponse\x12"\n\x05match\x18\x01 \x01(\x0b\x32\x13.matchservice.Match"F\n\x12ListMatchesRequest\x12\x30\n\rstatus_filter\x18\x01 \x01(\x0e\x32\x19.matchservice.MatchStatus";\n\x13ListMatchesResponse\x12$\n\x07matches\x18\x01 \x03(\x0b\x32\x13.matchservice.Match*7\n\x0bMatchStatus\x12\x0c\n\x08UPCOMING\x10\x00\x12\x0b\n\x07ONGOING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32\xd5\x02\n\x0cMatchService\x12\x46\n\x08\x41\x64\x64Match\x12\x1d.matchservice.AddMatchRequest\x1a\x1b.matchservice.MatchResponse\x12T\n\x0fUpdateMatchTime\x12$.matchservice.UpdateMatchTimeRequest\x1a\x1b.matchservice.MatchResponse\x12S\n\x14MarkMatchAsCompleted\x12\x1e.matchservice.MarkMatchRequest\x1a\x1b.matchservice.MatchResponse\x12R\n\x0bListMatches\x12 .matchservice.ListMatchesRequest\x1a!.matchservice.ListMatchesResponseB\x1aZ\x18proto_gen/matchservicepbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "match_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\030proto_gen/matchservicepb"
    _globals["_MATCHSTATUS"]._serialized_start = 494
    _globals["_MATCHSTATUS"]._serialized_end = 549
    _globals["_MATCH"]._serialized_start = 37
    _globals["_MATCH"]._serialized_end = 149
    _globals["_ADDMATCHREQUEST"]._serialized_start = 151
    _globals["_ADDMATCHREQUEST"]._serialized_end = 218
    _globals["_UPDATEMATCHTIMEREQUEST"]._serialized_start = 220
    _globals["_UPDATEMATCHTIMEREQUEST"]._serialized_end = 274
    _globals["_MARKMATCHREQUEST"]._serialized_start = 276
    _globals["_MARKMATCHREQUEST"]._serialized_end = 306
    _globals["_MATCHRESPONSE"]._serialized_start = 308
    _globals["_MATCHRESPONSE"]._serialized_end = 359
    _globals["_LISTMATCHESREQUEST"]._serialized_start = 361
    _globals["_LISTMATCHESREQUEST"]._serialized_end = 431
    _globals["_LISTMATCHESRESPONSE"]._serialized_start = 433
    _globals["_LISTMATCHESRESPONSE"]._serialized_end = 492
    _globals["_MATCHSERVICE"]._serialized_start = 552
    _globals["_MATCHSERVICE"]._serialized_end = 893
# @@protoc_insertion_point(module_scope)
